packaging_format = 2

id = "gitlab-runner"
name = "GitLab Runner"
description.en = "Continuous integration tool to use with a GitLab instance (YNH or not)."
description.fr = "Outil d'intégration continue à utiliser avec une instance GitLab (YNH ou non)."

version = "16.5.0~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "MIT"
website = "https://gitlab.com/gitlab-org/gitlab-runner"
admindoc = "https://docs.gitlab.com/runner/"
code = "https://gitlab.com/gitlab-org/gitlab-runner"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.0"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.gitlab_url]
    ask.en = "Please enter the GitLab-CI coordinator URL"
    ask.fr = "Veuillez entrer l'URL du coordinateur GitLab-CI"
    help.en = "This URL can be retrieved at this location: GitLab Project->Settings->Runner or: Admin Area->Overview->Runners"
    help.fr = "Cet URL peut être récupéré à cet emplacement : Projet GitLab->Settings->Runner ou : Admin Area->Overview->Runners"
    type = "string"
    example = "https://gitlab.com/"

    [install.token]
    ask.en = "Please enter the GitLab-CI token for this Runner"
    ask.fr = "Veuillez entrer le jeton GitLab-CI pour ce Runner"
    help.en = "This token can be retrieved at this location: GitLab Project->Settings->Runner or: Admin Area->Overview->Runners"
    help.fr = "Ce token peut être récupéré à cet emplacement : Projet GitLab->Settings->Runner ou : Admin Area->Overview->Runners"
    type = "string"
    example = "xxx"

    [install.docker_image]
    ask.en = "Please enter the Docker image"
    ask.fr = "Veuillez entrer l'image du Docker"
    type = "string"
    example = "ruby:2.1"
    default = "alpine:latest"

[resources]
        [resources.sources.main]
        format = "deb"
        rename = "gitlab-runner.deb"
        arm64.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.5.0/downloads/packages/deb/gitlab-runner_aarch64.deb"
        arm64.sha256 = "9747f0f82ec099ce34b1b352a9b09fbe237ed710f22c273fe7c08b1a80494b33"
        amd64.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.5.0/downloads/packages/deb/gitlab-runner_amd64.deb"
        amd64.sha256 = "7b619273ef5b845407dd45a84c7a1e07442493f2d140c94720f6c47c3a403b48"
        armel.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.5.0/downloads/packages/deb/gitlab-runner_armel.deb"
        armel.sha256 = "8d78e75bf8b75b64d86aa5c05df47b0fc7941a7c953a2cf55a487d8c19ca1e10"
        armhf.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.5.0/downloads/packages/deb/gitlab-runner_armhf.deb"
        armhf.sha256 = "ff51a7962851c1447c20d4bacc5b3ef2eef038045f9849fde089b4225e67d1ba"
        i386.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.5.0/downloads/packages/deb/gitlab-runner_i386.deb"
        i386.sha256 = "271b0437223eba292a79b4c427bdbca3c5edd578292149526b2bec5eb27d8c57"


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
