#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gitlab-runner"
name = "GitLab Runner"
description.en = "Continuous integration tool to use with a GitLab instance (YNH or not)"
description.fr = "Outil d'intégration continue à utiliser avec une instance GitLab (YNH ou non)"

version = "16.8.1~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "MIT"
website = "https://gitlab.com/gitlab-org/gitlab-runner"
admindoc = "https://docs.gitlab.com/runner/"
code = "https://gitlab.com/gitlab-org/gitlab-runner"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "i386", "armhf", "arm64"]
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.gitlab_url]
    ask.en = "Please enter the GitLab-CI coordinator URL"
    ask.fr = "Veuillez entrer l'URL du coordinateur GitLab-CI"
    help.en = "This URL can be retrieved at this location: GitLab Project->Settings->Runner or: Admin Area->Overview->Runners"
    help.fr = "Cet URL peut être récupéré à cet emplacement : Projet GitLab->Settings->Runner ou : Admin Area->Overview->Runners"
    type = "string"
    example = "https://gitlab.com/"

    [install.token]
    ask.en = "Please enter the GitLab-CI token for this Runner"
    ask.fr = "Veuillez entrer le jeton GitLab-CI pour ce Runner"
    help.en = "This token can be retrieved at this location: GitLab Project->Settings->Runner or: Admin Area->Overview->Runners"
    help.fr = "Ce token peut être récupéré à cet emplacement : Projet GitLab->Settings->Runner ou : Admin Area->Overview->Runners"
    type = "string"
    example = "xxx"

    [install.docker_image]
    ask.en = "Please enter the Docker image"
    ask.fr = "Veuillez entrer l'image du Docker"
    type = "string"
    example = "ruby:2.1"
    default = "alpine:latest"

[resources]
    [resources.sources.main]
    rename = "gitlab-runner.deb"
    amd64.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.8.1/downloads/packages/deb/gitlab-runner_amd64.deb"
    amd64.sha256 = "070aab90fbe8d574521b17415fecb6bdbd710662a41bbea2e94e514e9a260569"
    i386.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.8.1/downloads/packages/deb/gitlab-runner_i386.deb"
    i386.sha256 = "8868c3f8bfd42a3e2470a19c63297b4266f9ed33c159edf9df7dc7ea676fb301"
    arm64.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.8.1/downloads/packages/deb/gitlab-runner_arm64.deb"
    arm64.sha256 = "4820743e821ca2a9e2bf4166187e09aa49d131f3a96e626b382ab94a230170e6"
    armhf.url = "https://gitlab.com/gitlab-org/gitlab-runner/-/releases/v16.8.1/downloads/packages/deb/gitlab-runner_armhf.deb"
    armhf.sha256 = "687f738a52e97e3fb5f4b7b5ea728de4022c4acca4b59ccbf02e6ac76f8d4a46"

    autoupdate.upstream = "https://gitlab.com/gitlab-org/gitlab-runner"
    autoupdate.strategy = "latest_gitlab_release"
    autoupdate.asset.amd64 = "package: DEB amd64"
    autoupdate.asset.i386 = "package: DEB i386"
    autoupdate.asset.arm64 = "package: DEB arm64"
    autoupdate.asset.armhf = "package: DEB armhf"

    [resources.system_user]

    [resources.install_dir]

    [resources.apt]
    packages = [
        "ca-certificates",
        "git",
        "curl",
        "tar",
    ]

    extras.docker.repo = "https://download.docker.com/linux/debian bullseye stable"
    extras.docker.key = "https://download.docker.com/linux/debian/gpg"
    extras.docker.packages = "docker-ce, docker-ce-cli, containerd.io"
